
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author TEST
 */
public class PayBills extends javax.swing.JFrame {

/**
 * Creates new form PayBills
 */
public PayBills() {
    initComponents();
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/bill.png"))); //FOR ICON 
    setDetails();
}

public void setDetails() {
    int bill = BillInfo.getAmt();
    lbl_bill.setText("₹ " + String.valueOf(bill));
    LocalDate currentDate = LocalDate.now();
    LocalDate dueDate = LocalDate.of(currentDate.getYear(), currentDate.getMonth(), 19);
    if ((currentDate.isBefore(dueDate)) || currentDate.isEqual(dueDate)) {
        lbl_rew_or_penal.setText("Reward (-₹50)");
        int reward = bill - 50;
        int id = Login.getUser_id();
        try {
            Connection conn = DbConn.getConnection();
            PreparedStatement pst = conn.prepareStatement("update ebs.consumption set bill_amt=?,reward='50' where user_id=?");
            pst.setInt(1, reward);
            pst.setInt(2, id);
            int rowcount = pst.executeUpdate();
            if (rowcount > 0) {
                lbl_amt.setText("₹ " + String.valueOf(reward));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    } else {
        lbl_rew_or_penal.setText("Penalty (+₹100)");
        int penalty = bill + 100;
        int id = Login.getUser_id();
        try {
            Connection conn = DbConn.getConnection();
            PreparedStatement pst = conn.prepareStatement("update ebs.consumption set bill_amt=?,penalty='100' where user_id=?");
            pst.setInt(1, penalty);
            pst.setInt(2, id);
            int rowcount = pst.executeUpdate();
            if (rowcount > 0) {
                lbl_amt.setText("₹ " + String.valueOf(penalty));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

public boolean statusCheck() {
    boolean check = false;
    int id = Login.getUser_id();
    try {
        Connection conn = DbConn.getConnection();
        PreparedStatement pst = conn.prepareStatement("select status from ebs.consumption where user_id=?");
        pst.setInt(1, id);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            String stats = rs.getString("status");
            if (stats.equals("paid")) {
                check = true;
            } else {
                check = false;
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return check;
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_bill = new javax.swing.JLabel();
        lbl_rew_or_penal = new javax.swing.JLabel();
        lbl_amt = new javax.swing.JLabel();
        btn_pay = new rojerusan.RSMaterialButtonCircle();
        btn_back = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pay Bill");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Base Bill");

        lbl_bill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_bill.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bill.setText("asdasd");

        lbl_rew_or_penal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_rew_or_penal.setForeground(new java.awt.Color(0, 0, 0));
        lbl_rew_or_penal.setText("asdasd");

        lbl_amt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_amt.setForeground(new java.awt.Color(0, 0, 0));
        lbl_amt.setText("asdasd");

        btn_pay.setText("Pay");
        btn_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(0, 102, 102));
        btn_back.setText("back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_rew_or_penal, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addGap(137, 137, 137)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_amt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btn_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_amt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rew_or_penal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        BillInfo bill = new BillInfo();
        bill.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payActionPerformed
        // TODO add your handling code here:
        int id = Login.getUser_id();
        if (statusCheck() == false) {
            try {
                Connection conn = DbConn.getConnection();
                PreparedStatement pst = conn.prepareStatement("update ebs.consumption set status='paid' where user_id=?");
                pst.setInt(1, id);
                int rowcount = pst.executeUpdate();
                if (rowcount > 0) {
                    JOptionPane.showMessageDialog(this, "Electricity Bill Paid Successfully!!!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "You have already paid the bill!!!", "WARNING", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btn_payActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(PayBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(PayBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(PayBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(PayBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new PayBills().setVisible(true);
    }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btn_back;
    private rojerusan.RSMaterialButtonCircle btn_pay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_amt;
    private javax.swing.JLabel lbl_bill;
    private javax.swing.JLabel lbl_rew_or_penal;
    // End of variables declaration//GEN-END:variables
}
